apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: test
  labels:
    app: cat
    service: payment2
  annotations:
    test: test
spec:
  type: ClusterIP
  selector:
    app: cat
    service: payment2
  ports:
  - port: 8083
    targetPort: 80
    protocol: TCP
